### ISSUE TITLE
Instruction?

### ISSUE THREAD

**Issue by Justdigit** [hkayy/Logitech-WLED-Sync#3]
Hi,

Can you give some more expplaination to build??? or maybe you can provide the end program?? I am a bit of a noob. 
Just got my pc case fans ready with w led and would be nice if my Keyboards en mouses could sync.

**Comment by testudor** [comment]
Hi,

I just created a release with attached binary. Let me know if it works!

**Comment by Justdigit** [comment]
> Hi,
> 
> I just created a release with attached binary. Let me know if it works!

Yeah!! It works. Many thanks.
