### ISSUE TITLE
Two-way syncing?

### ISSUE THREAD

**Issue by rpbras** [hkayy/Logitech-WLED-Sync#4]
I’m experimenting with the logitech syncing app. Is it possible to use it for syncing from Logitech to WLED, too? At the moment I only got the sync from WLED to Logitech working.

**Comment by testudor** [comment]
Thanks for checking out my app :)

No, syncing from Logitech to WLED is not possible right now, I'm afraid. The official Logitech RGB SDK that I'm using only allows taking full control. You can't intercept lighting effects from the G Hub and then synchronize WLED to that. 

A solution to your use case might be [OpenRGB](https://gitlab.com/CalcProgrammer1/OpenRGB). It supports the E1.31 protocol and various Logitech devices. You'd still be replacing G Hub but OpenRGB has similar effects.
